### ISSUE TITLE
pywin32 not working on python 3.10

### ISSUE THREAD

**Issue by TheWebs** [SteveKiller/ApexFarming#1]
pywin32 is not supported on python 3.10. As you are only using it in the custom click function you could remove that dependency entirely if you use pyautogui.click() instead :)

**Comment by DMPR-dev** [comment]
install python 3.9 or lower

**Comment by SteveKiller** [comment]
> pywin32 is not supported on python 3.10. As you are only using it in the custom click function you could remove that dependency entirely if you use pyautogui.click() instead :)

That is a very good idea i well do this and update anything else
